# Generated by Django 5.2.8 on 2025-11-14 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Projekt neve')),
                ('location', models.CharField(max_length=255, verbose_name='Helyszín (cím)')),
                ('client', models.CharField(blank=True, max_length=150, verbose_name='Ügyfél neve')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Kezdés dátuma')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tervezett befejezés')),
                ('status', models.CharField(choices=[('TERVEZES', 'Tervezés alatt'), ('FOLYAMATBAN', 'Folyamatban'), ('BEFEJEZETT', 'Befejezett'), ('LEZART', 'Lezárt (Pénzügyileg is)')], default='TERVEZES', max_length=20, verbose_name='Státusz')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Költségvetés (Ft)')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projektek',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Feladat neve')),
                ('description', models.TextField(blank=True, verbose_name='Részletes leírás')),
                ('status', models.CharField(choices=[('FUGGO', 'Függőben'), ('FOLYAMATBAN', 'Folyamatban'), ('FELULVIZSG', 'Felülvizsgálat alatt'), ('KESZ', 'Kész')], default='FUGGO', max_length=20, verbose_name='Státusz')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Határidő')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='Kapcsolódó Projekt')),
            ],
            options={
                'verbose_name': 'Feladat',
                'verbose_name_plural': 'Feladatok',
                'ordering': ['due_date'],
            },
        ),
    ]
