# Generated by Django 5.2.8 on 2025-11-23 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetelszam', models.CharField(max_length=100, unique=True)),
                ('leiras', models.TextField()),
                ('egyseg', models.CharField(max_length=20)),
                ('normaido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fix_anyag_ar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('engy_kod', models.CharField(blank=True, max_length=50, null=True)),
                ('k_jelzo', models.CharField(blank=True, max_length=50, null=True)),
                ('cpr_kod', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('unit', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Munkanem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Projekt neve')),
                ('status', models.CharField(choices=[('UJ_KERES', '1. Új Megkeresés (Lead)'), ('FELMERES', '2. Felmérés alatt'), ('AJANLAT', '3. Ajánlattétel'), ('ELOKESZITES', '4. Projekt Előkészítés'), ('KIVITELEZES', '5. Kivitelezés (Lebonyolítás)'), ('ATADAS', '6. Műszaki Átadás-Átvétel'), ('LEZART', '7. Lezárt (Sikeres)'), ('ELUTASITVA', '8. Elutasítva / Meghiúsult')], default='UJ_KERES', max_length=20, verbose_name='Státusz')),
                ('location', models.CharField(max_length=255, verbose_name='Helyszín')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='Megrendelő Neve')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Telefonszám')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email cím')),
                ('contact_address', models.CharField(blank=True, max_length=255, verbose_name='Számlázási Cím')),
                ('client', models.CharField(blank=True, max_length=150, verbose_name='Ügyfél (Régi)')),
                ('inquiry_date', models.DateField(blank=True, null=True, verbose_name='Beérkezés')),
                ('callback_date', models.DateField(blank=True, null=True, verbose_name='Visszahívás')),
                ('survey_date', models.DateField(blank=True, null=True, verbose_name='Felmérés')),
                ('quote_date', models.DateField(blank=True, null=True, verbose_name='Ajánlattétel')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='Szerződés')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Kezdés')),
                ('handover_date', models.DateField(blank=True, null=True, verbose_name='Átadás')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Befejezés')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Keret')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=5000, max_digits=10, verbose_name='Rezsíóabér')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=27.0, max_digits=5, verbose_name='ÁFA %')),
                ('hours_per_day', models.DecimalField(decimal_places=2, default=8.0, max_digits=4, verbose_name='Napi óra')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projektek',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ItemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('master_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='projects.masteritem')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.material')),
            ],
        ),
        migrations.AddField(
            model_name='masteritem',
            name='munkanem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.munkanem'),
        ),
        migrations.CreateModel(
            name='Alvallalkozo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=200)),
                ('munkanem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.munkanem')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('amount_netto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('ANYAG', 'Anyagköltség'), ('MUNKADIJ', 'Munkadíj'), ('EGYEB', 'Egyéb')], default='ANYAG', max_length=20)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('weather', models.CharField(choices=[('NAPOS', 'Napos'), ('FELHOS', 'Felhős'), ('ESOS', 'Esős')], default='NAPOS', max_length=10)),
                ('workforce', models.PositiveIntegerField(default=0)),
                ('work_done', models.TextField()),
                ('problems', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='projects.project')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.supplier'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(default='FUGGO', max_length=20)),
                ('due_date', models.DateField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Tetelsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorszam', models.CharField(blank=True, max_length=50)),
                ('leiras', models.TextField(default='', verbose_name='Leírás')),
                ('mennyiseg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('egyseg', models.CharField(default='', max_length=20, verbose_name='Egység')),
                ('normaido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('anyag_egysegar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('megjegyzes', models.TextField(blank=True, null=True)),
                ('engy_kod', models.CharField(blank=True, max_length=50, null=True)),
                ('k_jelzo', models.CharField(blank=True, max_length=50, null=True)),
                ('cpr_kod', models.CharField(blank=True, max_length=50, null=True)),
                ('labor_split_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('anyag_osszesen', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dij_egysegre_sajat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dij_egysegre_alv', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sajat_munkadij_osszesen', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('alv_munkadij_osszesen', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('alvallalkozo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.alvallalkozo')),
                ('master_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.masteritem', verbose_name='Törzs Tétel')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.material')),
                ('munkanem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.munkanem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tetelsorok', to='projects.project')),
            ],
            options={
                'verbose_name': 'Projekt Tétel',
                'verbose_name_plural': 'Projekt Tételek',
            },
        ),
    ]
