# Generated by Django 5.2.8 on 2025-12-03 07:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Saját Kft.', max_length=200)),
                ('tax_number', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logo/')),
                ('head_country_code', models.CharField(default='H', max_length=5)),
                ('head_zip_code', models.CharField(default='', max_length=10)),
                ('head_city', models.CharField(default='', max_length=100)),
                ('head_street', models.CharField(default='', max_length=100)),
                ('head_house_number', models.CharField(default='', max_length=20)),
                ('head_floor', models.CharField(blank=True, max_length=20, null=True)),
                ('head_door', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weather', models.CharField(choices=[('NAPOS', 'Napos'), ('FELHOS', 'Felhős'), ('ESOS', 'Esős')], default='NAPOS', max_length=10)),
                ('workforce', models.PositiveIntegerField(default=0)),
                ('work_done', models.TextField()),
                ('problems', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Név')),
                ('position', models.CharField(max_length=100, verbose_name='Pozíció')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('daily_cost', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Napi Bérköltség (Ft)')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='Adóazonosító')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Lakcím')),
                ('registration_form', models.FileField(blank=True, null=True, upload_to='hr_docs/', verbose_name='Bejelentő lap')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='hr_docs/', verbose_name='Munkaszerződés')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktív'), ('INACTIVE', 'Inaktív')], default='ACTIVE', max_length=20, verbose_name='Státusz')),
                ('joined_date', models.DateField(blank=True, null=True, verbose_name='Belépés dátuma')),
            ],
            options={
                'verbose_name': 'Dolgozó',
                'verbose_name_plural': 'Dolgozók',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(default='óra', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='MasterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetelszam', models.CharField(max_length=100, unique=True)),
                ('leiras', models.TextField()),
                ('egyseg', models.CharField(max_length=20)),
                ('fix_anyag_ar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fix_munkadij', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fix_gep_ar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('normaido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('engy_kod', models.CharField(blank=True, max_length=50)),
                ('k_jelzo', models.CharField(blank=True, max_length=50)),
                ('cpr_kod', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Törzs Tétel',
                'verbose_name_plural': 'Törzs Tételek',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('unit', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='TERVEZET', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Munkanem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Projekt neve')),
                ('status', models.CharField(choices=[('UJ_KERES', '1. Új Megkeresés (Lead)'), ('FELMERES', '2. Felmérés alatt'), ('AJANLAT', '3. Ajánlattétel'), ('ELOKESZITES', '4. Projekt Előkészítés'), ('KIVITELEZES', '5. Kivitelezés'), ('ATADAS', '6. Átadás'), ('LEZART', '7. Lezárt'), ('ELUTASITVA', '8. Elutasítva'), ('TORLES_KERELEM', '9. Törlésre vár')], default='UJ_KERES', max_length=20, verbose_name='Státusz')),
                ('location', models.CharField(max_length=255, verbose_name='Helyszín')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='Megrendelő Neve')),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_address', models.CharField(blank=True, max_length=255)),
                ('client', models.CharField(blank=True, max_length=150)),
                ('is_company', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('tax_number', models.CharField(blank=True, max_length=50)),
                ('inquiry_date', models.DateField(blank=True, null=True)),
                ('callback_date', models.DateField(blank=True, null=True)),
                ('survey_date', models.DateField(blank=True, null=True)),
                ('quote_date', models.DateField(blank=True, null=True)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('handover_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=27.0, max_digits=5)),
                ('hours_per_day', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projektek',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_city', models.CharField(max_length=100)),
                ('site_zip_code', models.CharField(max_length=10)),
                ('site_street', models.CharField(max_length=100)),
                ('site_country_code', models.CharField(default='H', max_length=5)),
                ('site_house_number', models.CharField(default='', max_length=20)),
                ('site_floor', models.CharField(blank=True, max_length=20, null=True)),
                ('site_door', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='projects.companysettings')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='daily_logs/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.dailylog')),
            ],
        ),
        migrations.CreateModel(
            name='MachineComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.machine')),
                ('master_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_components', to='projects.masteritem')),
            ],
        ),
        migrations.CreateModel(
            name='ItemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('master_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_components', to='projects.masteritem')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.material')),
            ],
        ),
        migrations.AddField(
            model_name='masteritem',
            name='munkanem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.munkanem'),
        ),
        migrations.CreateModel(
            name='Alvallalkozo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=200)),
                ('munkanem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.munkanem')),
            ],
        ),
        migrations.CreateModel(
            name='LaborComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('master_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_components', to='projects.masteritem')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.operation')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.materialorder')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Dátum')),
                ('type', models.CharField(choices=[('ADVANCE', '💰 Előleg'), ('PREMIUM', '🏆 Prémium'), ('DEDUCTION', '🔻 Levonás'), ('VACATION', '🏖️ Szabadság'), ('SICK_LEAVE', '🤒 Betegszabadság')], max_length=20, verbose_name='Típus')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Összeg (Ft)')),
                ('note', models.TextField(blank=True, verbose_name='Megjegyzés')),
                ('approved', models.BooleanField(default=False, verbose_name='Jóváhagyva')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.employee', verbose_name='Dolgozó')),
            ],
            options={
                'verbose_name': 'Bér Tétel',
                'verbose_name_plural': 'Bér Tételek',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='materialorder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_orders', to='projects.project'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('amount_netto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('ANYAG', 'Anyag'), ('MUNKADIJ', 'Munkadíj'), ('EGYEB', 'Egyéb')], default='ANYAG', max_length=20)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='dailylog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='projects.project'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Dátum')),
                ('hours_worked', models.DecimalField(decimal_places=1, default=8.0, max_digits=4, verbose_name='Ledolgozott óra')),
                ('gps_lat', models.CharField(blank=True, max_length=50, null=True, verbose_name='GPS Szél.')),
                ('gps_lon', models.CharField(blank=True, max_length=50, null=True, verbose_name='GPS Hossz.')),
                ('check_in_photo', models.ImageField(blank=True, null=True, upload_to='attendance_photos/%Y/%m/', verbose_name='Fotó')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.employee', verbose_name='Dolgozó')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Munkaterület')),
            ],
            options={
                'verbose_name': 'Jelenlét',
                'verbose_name_plural': 'Jelenléti Ívek',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Fejezet neve')),
                ('rank', models.IntegerField(default=0, verbose_name='Sorrend')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='projects.project')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_docs/%Y/%m/')),
                ('category', models.CharField(default='EGYEB', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DailyMaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_usages', to='projects.dailylog')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectinventory')),
            ],
        ),
        migrations.CreateModel(
            name='Signatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(default='Ügyvezető', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatories', to='projects.companysettings')),
            ],
        ),
        migrations.AddField(
            model_name='materialorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.supplier'),
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.supplier'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(default='FUGGO', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Tetelsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorszam', models.CharField(blank=True, max_length=50)),
                ('leiras', models.TextField(default='')),
                ('mennyiseg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('egyseg', models.CharField(default='', max_length=20)),
                ('normaido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('anyag_egysegar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('megjegyzes', models.TextField(blank=True, null=True)),
                ('engy_kod', models.CharField(blank=True, max_length=50)),
                ('k_jelzo', models.CharField(blank=True, max_length=50)),
                ('cpr_kod', models.CharField(blank=True, max_length=50)),
                ('labor_split_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('anyag_osszesen', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dij_egysegre_sajat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dij_egysegre_alv', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sajat_munkadij_osszesen', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('alv_munkadij_osszesen', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gantt_start_date', models.DateField(blank=True, null=True)),
                ('gantt_duration', models.IntegerField(default=1)),
                ('felelos', models.CharField(blank=True, max_length=100)),
                ('alvallalkozo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.alvallalkozo')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.projectchapter', verbose_name='Fejezet')),
                ('master_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.masteritem')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.material')),
                ('munkanem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.munkanem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tetelsorok', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='GanttLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='0', max_length=2)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='projects.tetelsor')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_links', to='projects.tetelsor')),
            ],
        ),
        migrations.CreateModel(
            name='UniclassNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title_en', models.CharField(max_length=255)),
                ('title_hu', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('date', models.CharField(blank=True, max_length=20)),
                ('extra_data', models.TextField(blank=True)),
                ('table', models.CharField(max_length=10)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.uniclassnode')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='operation',
            name='uniclass_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.uniclassnode'),
        ),
        migrations.AddField(
            model_name='material',
            name='uniclass_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.uniclassnode'),
        ),
        migrations.AddField(
            model_name='masteritem',
            name='uniclass_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.uniclassnode'),
        ),
        migrations.AddField(
            model_name='machine',
            name='uniclass_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.uniclassnode'),
        ),
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together={('project', 'date')},
        ),
    ]
