# Generated by Django 5.2.8 on 2025-11-21 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailylog',
            options={'ordering': ['-date'], 'verbose_name': 'Napi Jelentés', 'verbose_name_plural': 'Napi Jelentések'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date'], 'verbose_name': 'Kiadás / Számla', 'verbose_name_plural': 'Kiadások'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status', 'due_date'], 'verbose_name': 'Feladat', 'verbose_name_plural': 'Feladatok'},
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kapcsolattartó'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefonszám'),
        ),
        migrations.AddField(
            model_name='tetelsor',
            name='anyag_egysegar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Anyag Egységár'),
        ),
        migrations.AddField(
            model_name='tetelsor',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.material', verbose_name='Kapcsolódó Anyag'),
        ),
        migrations.AlterField(
            model_name='alvallalkozo',
            name='munkanem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.munkanem', verbose_name='Kapcsolódó munkanem'),
        ),
        migrations.AlterField(
            model_name='alvallalkozo',
            name='nev',
            field=models.CharField(max_length=200, verbose_name='Alvállalkozó neve'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='date',
            field=models.DateField(unique=True, verbose_name='Dátum'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='problems',
            field=models.TextField(blank=True, null=True, verbose_name='Problémák / Események'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='projects.project', verbose_name='Projekt'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='weather',
            field=models.CharField(choices=[('NAPOS', 'Napos'), ('FELHOS', 'Felhős'), ('ESOS', 'Esős'), ('HAVAS', 'Havas'), ('SZEL', 'Szeles')], default='NAPOS', max_length=10, verbose_name='Időjárás'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='work_done',
            field=models.TextField(verbose_name='Elvégzett munka / Haladás'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='workforce',
            field=models.PositiveIntegerField(default=0, verbose_name='Jelenlévő munkaerő (fő)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount_netto',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Nettó összeg (Ft)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ANYAG', 'Anyagköltség'), ('MUNKADIJ', 'Munkadíj'), ('EGYEB', 'Egyéb / Általános')], default='ANYAG', max_length=20, verbose_name='Kategória'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name='Fizetés/Számla dátuma'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/', verbose_name='Számla kép/PDF'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tétel megnevezése / Számlaszám'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project', verbose_name='Kapcsolódó Projekt'),
        ),
        migrations.AlterField(
            model_name='itemcomponent',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Szükséges mennyiség'),
        ),
        migrations.AlterField(
            model_name='itemcomponent',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.material', verbose_name='Alapanyag'),
        ),
        migrations.AlterField(
            model_name='masteritem',
            name='egyseg',
            field=models.CharField(max_length=20, verbose_name='Egység (ME)'),
        ),
        migrations.AlterField(
            model_name='masteritem',
            name='fix_anyag_ar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Importált/Fix Anyagár'),
        ),
        migrations.AlterField(
            model_name='masteritem',
            name='leiras',
            field=models.TextField(verbose_name='Tétel leírása'),
        ),
        migrations.AlterField(
            model_name='masteritem',
            name='normaido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Normaidő (óra)'),
        ),
        migrations.AlterField(
            model_name='masteritem',
            name='tetelszam',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tételszám (KULCS)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Anyag neve/kódja'),
        ),
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Aktuális egységár (Nettó)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.supplier', verbose_name='Fő Beszállító'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='Egység (pl. db, m3, zsák)'),
        ),
        migrations.AlterField(
            model_name='munkanem',
            name='nev',
            field=models.CharField(max_length=150, unique=True, verbose_name='Munkanem neve'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Beszállító neve'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Részletes leírás'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Határidő'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Feladat neve'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='Kapcsolódó Projekt'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('FUGGO', 'Függőben'), ('FOLYAMATBAN', 'Folyamatban'), ('FELULVIZSG', 'Felülvizsgálat alatt'), ('KESZ', 'Kész')], default='FUGGO', max_length=20, verbose_name='Státusz'),
        ),
        migrations.AlterField(
            model_name='tetelsor',
            name='labor_split_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='Saját munka felosztás (%)'),
        ),
        migrations.AlterField(
            model_name='tetelsor',
            name='mennyiseg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mennyiség'),
        ),
        migrations.AlterField(
            model_name='tetelsor',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Készültségi fok (%)'),
        ),
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together={('project', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='tetelsor',
            unique_together={('project', 'master_item')},
        ),
    ]
