# Generated by Django 5.2.8 on 2025-11-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Saját Építőipari Kft.', max_length=200, verbose_name='Cégnév')),
                ('address', models.CharField(default='1234 Budapest, Fő utca 1.', max_length=255, verbose_name='Cím')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='Adószám')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefonszám')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email cím')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logo/', verbose_name='Céges Logó')),
            ],
            options={
                'verbose_name': 'Cégbeállítások',
                'verbose_name_plural': 'Cégbeállítások',
            },
        ),
    ]
