# Generated by Django 5.2.8 on 2025-11-14 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Munkanem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=150, unique=True, verbose_name='Munkanem neve')),
            ],
            options={
                'verbose_name': 'Munkanem',
                'verbose_name_plural': 'Munkanemek',
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status', 'due_date'], 'verbose_name': 'Feladat', 'verbose_name_plural': 'Feladatok'},
        ),
        migrations.AddField(
            model_name='project',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10, verbose_name='Rezsíóabér (Ft/óra)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('TERVEZES', 'Tervezés alatt'), ('FOLYAMATBAN', 'Folyamatban'), ('BEFEJEZETT', 'Befejezett'), ('LEZART', 'Lezárt (Pénzügyileg is)'), ('TORLES_KERELEM', 'Törlés Kérelmezve')], default='TERVEZES', max_length=20, verbose_name='Státusz'),
        ),
        migrations.CreateModel(
            name='Alvallalkozo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=200, verbose_name='Alvállalkozó neve')),
                ('munkanem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.munkanem', verbose_name='Kapcsolódó munkanem')),
            ],
            options={
                'verbose_name': 'Alvállalkozó',
                'verbose_name_plural': 'Alvállalkozók',
            },
        ),
        migrations.CreateModel(
            name='Tetelsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorszam', models.CharField(blank=True, max_length=50, verbose_name='Sorszám')),
                ('tetelszam', models.CharField(db_index=True, max_length=100, verbose_name='Tételszám')),
                ('leiras', models.TextField(verbose_name='Leírás (Feladat)')),
                ('mennyiseg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mennyiség')),
                ('egyseg', models.CharField(blank=True, max_length=20, verbose_name='Egység (ME)')),
                ('anyag_egysegar', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Anyag Egységár')),
                ('dij_egysegre', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Díj Egységre')),
                ('anyag_osszesen', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Anyag Összesen')),
                ('dij_osszesen', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Díj Összesen')),
                ('megjegyzes', models.TextField(blank=True, null=True, verbose_name='Megjegyzés')),
                ('engy_kod', models.CharField(blank=True, max_length=50, null=True, verbose_name='ÉNGY kód')),
                ('k_jelzo', models.CharField(blank=True, max_length=50, null=True, verbose_name='K.jelző')),
                ('normaido', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Normaidő (óra)')),
                ('cpr_kod', models.CharField(blank=True, max_length=50, null=True, verbose_name='CPR kód')),
                ('alvallalkozo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.alvallalkozo', verbose_name='Alvállalkozó')),
                ('munkanem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.munkanem', verbose_name='Munkanem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tetelsorok', to='projects.project', verbose_name='Kapcsolódó Projekt')),
            ],
            options={
                'verbose_name': 'Tételsor',
                'verbose_name_plural': 'Tételsorok',
                'unique_together': {('project', 'tetelszam')},
            },
        ),
    ]
