# Generated by Django 5.2.8 on 2025-12-03 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='projectinventory',
            unique_together=set(),
        ),
        # Attendance table is already created in 0001_initial; keep only field changes below.
        migrations.AddField(
            model_name='attendance',
            name='end_time',
            field=models.TimeField(default='16:00', verbose_name='Befejezés'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_abroad',
            field=models.BooleanField(default=False, verbose_name='Külföld'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_driver',
            field=models.BooleanField(default=False, verbose_name='Sofőr'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='start_time',
            field=models.TimeField(default='07:00', verbose_name='Kezdés'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Felhasználói Fiók'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='hours_worked',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Ledolgozott óra'),
        ),
        migrations.AlterField(
            model_name='companysite',
            name='site_zip_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
