# Generated by Django 5.2.8 on 2025-12-03 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_task_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Dátum')),
                ('name', models.CharField(max_length=100, verbose_name='Ünnep neve (pl. Karácsony)')),
                ('is_workday', models.BooleanField(default=False, verbose_name='Munkanap? (Szombati ledolgozás)')),
            ],
            options={
                'verbose_name': 'Ünnepnap / Munkarend',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('WORK', '✅ Jelen (Munka)'), ('SZ', '🟢 Fizetett Szabadság'), ('B', '🔴 Betegszabadság'), ('F', '⚪ Fizetés nélküli'), ('I', '⚫ Igazolatlan'), ('K', '🔵 Kiküldetés / Külföld'), ('TP', '📚 Tanulmányi szabadság'), ('CS', '⏳ Csúsztatás')], default='WORK', max_length=5, verbose_name='Típus'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in_photo',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_photos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='gps_lat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='gps_lon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Munkaterület'),
        ),
        migrations.AlterField(
            model_name='payrollitem',
            name='type',
            field=models.CharField(choices=[('ADVANCE', '💰 Előleg'), ('PREMIUM', '🏆 Prémium'), ('DEDUCTION', '🔻 Levonás'), ('VACATION', '🏖️ Szabadság kifizetés'), ('SICK_LEAVE', '🤒 Táppénz kieg.')], max_length=20, verbose_name='Típus'),
        ),
        migrations.CreateModel(
            name='AttendanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='Időpont')),
                ('original_value', models.TextField(verbose_name='Eredeti érték')),
                ('new_value', models.TextField(verbose_name='Új érték')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Módosítás oka')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='projects.attendance')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Módosító')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2025, verbose_name='Év')),
                ('base_leave', models.IntegerField(default=20, verbose_name='Alapszabadság')),
                ('age_leave', models.IntegerField(default=0, verbose_name='Életkor utáni pótszab.')),
                ('child_leave', models.IntegerField(default=0, verbose_name='Gyermek utáni pótszab.')),
                ('carry_over', models.IntegerField(default=0, verbose_name='Tavalyról áthozott')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='projects.employee')),
            ],
            options={
                'verbose_name': 'Szabadság Egyenleg',
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
