# Generated by Django 5.2.8 on 2025-11-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_munkanem_alter_task_options_project_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=27.0, max_digits=5, verbose_name='ÁFA kulcs (%)'),
        ),
    ]
