# Generated by Django 5.2.8 on 2025-11-23 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_companysettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alvallalkozo',
            options={'verbose_name': 'Alvállalkozó', 'verbose_name_plural': 'Alvállalkozók'},
        ),
        migrations.AlterModelOptions(
            name='companysettings',
            options={'verbose_name': 'Cégbeállítások (Székhely)', 'verbose_name_plural': 'Cégbeállítások (Székhely)'},
        ),
        migrations.AlterModelOptions(
            name='masteritem',
            options={'verbose_name': 'Törzs Tétel', 'verbose_name_plural': 'Törzs Tételek'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Anyag', 'verbose_name_plural': 'Anyagok'},
        ),
        migrations.AlterModelOptions(
            name='munkanem',
            options={'verbose_name': 'Munkanem', 'verbose_name_plural': 'Munkanemek'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Beszállító', 'verbose_name_plural': 'Beszállítók'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Feladat', 'verbose_name_plural': 'Feladatok'},
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='address',
        ),
        migrations.AddField(
            model_name='companysettings',
            name='head_city',
            field=models.CharField(default='', max_length=100, verbose_name='Helység név'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='head_country_code',
            field=models.CharField(default='H', max_length=5, verbose_name='Országkód'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='head_door',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ajtó'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='head_floor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Emelet'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='head_house_number',
            field=models.CharField(default='', max_length=20, verbose_name='Házszám / HRSZ'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='head_street',
            field=models.CharField(default='', max_length=100, verbose_name='Utca név'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='head_zip_code',
            field=models.CharField(default='', max_length=10, verbose_name='Irányítószám'),
        ),
        migrations.CreateModel(
            name='CompanySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_country_code', models.CharField(default='H', max_length=5, verbose_name='Országkód')),
                ('site_zip_code', models.CharField(max_length=10, verbose_name='Irányítószám')),
                ('site_city', models.CharField(max_length=100, verbose_name='Helység név')),
                ('site_street', models.CharField(max_length=100, verbose_name='Utca név')),
                ('site_house_number', models.CharField(max_length=20, verbose_name='Házszám / HRSZ')),
                ('site_floor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Emelet')),
                ('site_door', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ajtó')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='projects.companysettings')),
            ],
            options={
                'verbose_name': 'Telephely',
                'verbose_name_plural': 'Telephelyek',
            },
        ),
    ]
