# Generated by Django 5.2.8 on 2025-12-05

from django.db import migrations, models
from decimal import Decimal


def backfill_hourly_wage(apps, schema_editor):
    Employee = apps.get_model('projects', 'Employee')
    # Töltsük fel az órabért a meglévő napi_költség alapján (napi/8), ha 0 az órabér
    for emp in Employee.objects.all():
        try:
            current = Decimal(emp.hourly_wage or 0)
        except Exception:
            current = Decimal(0)
        if current and current > 0:
            continue
        try:
            daily = Decimal(emp.daily_cost or 0)
        except Exception:
            daily = Decimal(0)
        if daily and daily > 0:
            # Mivel az oszlop 0 tizedesjegyű Decimal, kerekítsünk egészre
            emp.hourly_wage = (daily / Decimal(8)).quantize(Decimal('1'))
            emp.save(update_fields=['hourly_wage'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_publicholiday_attendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hourly_wage',
            field=models.DecimalField(default=0, max_digits=10, decimal_places=0, verbose_name='Órabér (Ft)'),
        ),
        migrations.RunPython(backfill_hourly_wage, migrations.RunPython.noop),
    ]
