# Generated by Django 5.2.8 on 2025-11-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hours_per_day',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=4, verbose_name='Tervezett munkaóra / nap'),
        ),
    ]
