# Generated by Django 5.2.8 on 2025-12-03 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_publicholiday_attendance_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Kezdete')),
                ('end_date', models.DateField(verbose_name='Vége')),
                ('leave_type', models.CharField(choices=[('SZ', 'Fizetett Szabadság'), ('B', 'Betegszabadság'), ('F', 'Fizetés nélküli'), ('TP', 'Tanulmányi')], default='SZ', max_length=5, verbose_name='Típus')),
                ('reason', models.TextField(blank=True, verbose_name='Indoklás')),
                ('status', models.CharField(choices=[('PENDING', '⏳ Függőben'), ('APPROVED', '✅ Elfogadva'), ('REJECTED', '❌ Elutasítva')], default='PENDING', max_length=10, verbose_name='Státusz')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Elutasítás oka')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.employee', verbose_name='Dolgozó')),
            ],
            options={
                'verbose_name': 'Szabadság Kérelem',
                'verbose_name_plural': 'Szabadság Kérelmek',
                'ordering': ['-created_at'],
            },
        ),
    ]
