# Generated by Django 5.2.8 on 2025-11-23 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_alvallalkozo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Név')),
                ('position', models.CharField(default='Ügyvezető', max_length=100, verbose_name='Beosztás')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatories', to='projects.companysettings')),
            ],
            options={
                'verbose_name': 'Aláíró',
                'verbose_name_plural': 'Aláírásra Jogosultak',
            },
        ),
    ]
