# Generated by Django 5.2.8 on 2025-11-19 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_hours_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tétel megnevezése / Számlaszám')),
                ('date', models.DateField(verbose_name='Fizetés/Számla dátuma')),
                ('amount_netto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Nettó összeg (Ft)')),
                ('category', models.CharField(choices=[('ANYAG', 'Anyagköltség'), ('MUNKADIJ', 'Munkadíj'), ('EGYEB', 'Egyéb / Általános')], default='ANYAG', max_length=20, verbose_name='Kategória')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/', verbose_name='Számla kép/PDF')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project', verbose_name='Kapcsolódó Projekt')),
            ],
            options={
                'verbose_name': 'Kiadás / Számla',
                'verbose_name_plural': 'Kiadások',
                'ordering': ['-date'],
            },
        ),
    ]
