# Generated by Django 5.2.8 on 2025-11-23 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_signatory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_docs/%Y/%m/', verbose_name='Fájl')),
                ('category', models.CharField(choices=[('TERV', 'Tervrajz'), ('SZERZODES', 'Szerződés'), ('ENGEDELY', 'Hatósági Engedély'), ('FOTO', 'Helyszíni Fotó'), ('FELMERES', 'Felmérési Napló'), ('TELJESITES', 'Teljesítésigazolás'), ('EGYEB', 'Egyéb')], default='EGYEB', max_length=20, verbose_name='Kategória')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Feltöltve')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Leírás / Megnevezés')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
            options={
                'verbose_name': 'Dokumentum',
                'verbose_name_plural': 'Dokumentumok',
            },
        ),
    ]
