# Generated by Django 5.2.8 on 2025-12-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='leave_proofs/%Y/', verbose_name='Igazolás (Fotó/PDF)'),
        ),
    ]
