# Generated by Django 5.2.8 on 2025-11-24 17:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kapcsolattartó'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Beszállító Neve'),
        ),
        migrations.CreateModel(
            name='MaterialOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Rendelés dátuma')),
                ('status', models.CharField(choices=[('TERVEZET', 'Tervezet (Szerkesztés alatt)'), ('ELKULDVE', 'Elküldve (Várakozás)'), ('VISSZAIGAZOLVA', 'Visszaigazolva'), ('TELJESITVE', 'Teljesítve / Beérkezett'), ('LEMONDVA', 'Lemondva')], default='TERVEZET', max_length=20, verbose_name='Státusz')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzés')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_orders', to='projects.project')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.supplier', verbose_name='Beszállító')),
            ],
            options={
                'verbose_name': 'Anyagrendelés',
                'verbose_name_plural': 'Anyagrendelések',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Anyag neve')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mennyiség')),
                ('unit', models.CharField(max_length=20, verbose_name='Egység')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Becsült Egységár')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.materialorder')),
            ],
        ),
    ]
