# Generated by Django 5.2.8 on 2025-11-19 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Dátum')),
                ('weather', models.CharField(choices=[('NAPOS', 'Napos'), ('FELHOS', 'Felhős'), ('ESOS', 'Esős'), ('HAVAS', 'Havas'), ('SZEL', 'Szeles')], default='NAPOS', max_length=10, verbose_name='Időjárás')),
                ('workforce', models.PositiveIntegerField(default=0, verbose_name='Jelenlévő munkaerő (fő)')),
                ('work_done', models.TextField(verbose_name='Elvégzett munka / Haladás')),
                ('problems', models.TextField(blank=True, null=True, verbose_name='Problémák / Események')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='projects.project', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Napi Jelentés',
                'verbose_name_plural': 'Napi Jelentések',
                'ordering': ['-date'],
                'unique_together': {('project', 'date')},
            },
        ),
    ]
