# Generated by Django 5.2.8 on 2025-12-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_leaverequest_proof_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='check_in_photo',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='attendance',
            name='note',
            field=models.TextField(blank=True, verbose_name='Megjegyzés'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='sick_paper',
            field=models.FileField(blank=True, null=True, upload_to='sick_papers/%Y/', verbose_name='Orvosi igazolás'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Befejezés'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Kezdés'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('WORK', '✅ Munkavégzés történt'), ('WEATHER', '🌧️ Időjárás miatt állás'), ('SICK', '🤒 Betegszabadság'), ('ABSENCE', '🚨 Rendkívüli távollét'), ('OTHER', '❓ Egyéb ok')], default='WORK', max_length=10, verbose_name='Tevékenység'),
        ),
    ]
