# Generated by Django 5.2.8 on 2025-12-04 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_attendance_check_in_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ANYAG', '🧱 Anyag'), ('ESZKOZ', '🔨 Eszköz / Gép'), ('SZAKIPAR', '👷 Szakipar'), ('SUPPORT', '📐 Műszaki Támogatás')], default='ANYAG', max_length=10, verbose_name='Típus')),
                ('name', models.CharField(max_length=200, verbose_name='Megnevezés')),
                ('quantity', models.CharField(blank=True, max_length=50, verbose_name='Mennyiség')),
                ('description', models.TextField(blank=True, verbose_name='Részletes leírás')),
                ('status', models.CharField(choices=[('PENDING', '⏳ Függőben'), ('ORDERED', '🛒 Megrendelve'), ('DELIVERED', '✅ Szállítva / Teljesítve'), ('REJECTED', '❌ Elutasítva')], default='PENDING', max_length=10, verbose_name='Státusz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='projects.dailylog', verbose_name='Napló')),
            ],
            options={
                'verbose_name': 'Igénylés',
                'verbose_name_plural': 'Igénylések',
            },
        ),
        migrations.CreateModel(
            name='PlanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mappa neve')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='projects.plancategory', verbose_name='Szülő mappa')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_categories', to='projects.project')),
            ],
            options={
                'verbose_name': 'Terv Mappa',
                'verbose_name_plural': 'Terv Mappák',
            },
        ),
        migrations.CreateModel(
            name='PlanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Dokumentum neve')),
                ('file', models.FileField(upload_to='plans/%Y/%m/', verbose_name='Fájl')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.plancategory', verbose_name='Mappa')),
            ],
            options={
                'verbose_name': 'Tervrajz',
                'verbose_name_plural': 'Tervrajzok',
            },
        ),
    ]
