# Generated by Django 5.2.8 on 2025-11-19 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_dailylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Anyag neve/kódja')),
                ('unit', models.CharField(max_length=20, verbose_name='Egység (pl. db, m3, zsák)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Aktuális egységár (Nettó)')),
            ],
            options={
                'verbose_name': 'Anyag',
                'verbose_name_plural': 'Anyagok',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Beszállító neve')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='Kapcsolattartó')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefonszám')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Beszállító',
                'verbose_name_plural': 'Beszállítók',
            },
        ),
        migrations.RemoveField(
            model_name='tetelsor',
            name='anyag_egysegar',
        ),
        migrations.AddField(
            model_name='tetelsor',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.material', verbose_name='Kapcsolódó Anyag'),
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.supplier', verbose_name='Fő Beszállító'),
        ),
    ]
