# Generated by Django 5.2.8 on 2025-11-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_supplier_contact_person_supplier_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='dailylog',
            constraint=models.UniqueConstraint(fields=('project', 'date'), name='unique_daily_log_per_project_and_date'),
        ),
    ]
