# Generated by Django 5.2.8 on 2025-12-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_logrequest_plancategory_plandocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrequest',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Igény leírása'),
        ),
        migrations.AlterField(
            model_name='logrequest',
            name='type',
            field=models.CharField(choices=[('ANYAG', '🧱 Anyag'), ('ESZKOZ', '🔨 Eszköz / Gép'), ('SZAKIPAR', '👷 Szakipar'), ('SUPPORT', '📐 Műszaki támogatás')], default='ANYAG', max_length=10, verbose_name='Típus'),
        ),
    ]
