# Generated by Django 5.2.8 on 2025-11-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_dailylog_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cégnév (Ha céges)'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_company',
            field=models.BooleanField(default=False, verbose_name='Céges megrendelő?'),
        ),
        migrations.AddField(
            model_name='project',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Adószám'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ügyfél (Régi/Belső név)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Számlázási Cím (Székhely)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Kapcsolattartó Neve'),
        ),
    ]
