# Generated by Django 5.2.8 on 2025-11-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_material_supplier_remove_tetelsor_anyag_egysegar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tetelsor',
            name='dij_egysegre',
        ),
        migrations.RemoveField(
            model_name='tetelsor',
            name='dij_osszesen',
        ),
        migrations.AddField(
            model_name='tetelsor',
            name='alv_munkadij_osszesen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Alvállalkozói Díj Összesen'),
        ),
        migrations.AddField(
            model_name='tetelsor',
            name='dij_egysegre_alv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Díj Egységre (Alváll.)'),
        ),
        migrations.AddField(
            model_name='tetelsor',
            name='dij_egysegre_sajat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Díj Egységre (Saját)'),
        ),
        migrations.AddField(
            model_name='tetelsor',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Készültségi fok (%)'),
        ),
        migrations.AddField(
            model_name='tetelsor',
            name='sajat_munkadij_osszesen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saját Munkadíj Összesen'),
        ),
    ]
