# Generated by Django 5.2.8 on 2025-11-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_tetelsor_dij_egysegre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tetelsor',
            name='labor_split_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='Saját munka felosztás (%)'),
        ),
    ]
