# Generated by Django 5.1.6 on 2025-12-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_alter_logrequest_name_alter_logrequest_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logrequest",
            name="description",
        ),
        migrations.AlterField(
            model_name="logrequest",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Igény leírása"),
        ),
        migrations.AlterField(
            model_name="logrequest",
            name="quantity",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Mennyiség"
            ),
        ),
        migrations.AlterField(
            model_name="logrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "⏳ Függőben"),
                    ("ORDERED", "🛒 Megrendelve"),
                    ("DELIVERED", "✅ Teljesítve"),
                    ("REJECTED", "❌ Elutasítva"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="Státusz",
            ),
        ),
        migrations.AlterField(
            model_name="logrequest",
            name="type",
            field=models.CharField(
                choices=[
                    ("ANYAG", "🧱 Anyag"),
                    ("ESZKOZ", "🔨 Eszköz / Gép"),
                    ("SZAKIPAR", "👷 Szakipar"),
                    ("SUPPORT", "📐 Műszaki Támogatás"),
                ],
                default="ANYAG",
                max_length=10,
                verbose_name="Típus",
            ),
        ),
    ]
