# Generated by Django 5.2.8 on 2025-11-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_company_name_project_is_company_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailylog',
            name='unique_daily_log_per_project_and_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_company',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tax_number',
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ügyfél (Régi)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Számlázási Cím'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Megrendelő Neve'),
        ),
    ]
