# Generated by Django 5.1.6 on 2025-12-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0009_remove_logrequest_description_alter_logrequest_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["due_date"]},
        ),
        migrations.AlterUniqueTogether(
            name="projectinventory",
            unique_together={("project", "name")},
        ),
    ]
