# Generated by Django 5.2.8 on 2025-11-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_dailylog_unique_daily_log_per_project_and_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cégnév (Ha céges)'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_company',
            field=models.BooleanField(default=False, verbose_name='Céges megrendelő?'),
        ),
        migrations.AddField(
            model_name='project',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Adószám'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('UJ_KERES', '1. Új Megkeresés (Lead)'), ('FELMERES', '2. Felmérés alatt'), ('AJANLAT', '3. Ajánlattétel'), ('ELOKESZITES', '4. Projekt Előkészítés'), ('KIVITELEZES', '5. Kivitelezés (Lebonyolítás)'), ('ATADAS', '6. Műszaki Átadás-Átvétel'), ('LEZART', '7. Lezárt (Sikeres)'), ('ELUTASITVA', '8. Elutasítva / Meghiúsult'), ('TORLES_KERELEM', '9. Törlési kérelem alatt')], default='UJ_KERES', max_length=20, verbose_name='Státusz'),
        ),
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together={('project', 'date')},
        ),
    ]
