# Generated by Django 5.1.6 on 2025-12-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_alter_task_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tetelsor",
            unique_together={("project", "master_item")},
        ),
    ]
