# Generated by Django 5.2.8 on 2025-11-26 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_company_name_project_is_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialorder',
            name='status',
            field=models.CharField(choices=[('TERVEZET', 'Tervezet'), ('ELKULDVE', 'Elküldve'), ('VISSZAIGAZOLVA', 'Visszaigazolva'), ('TELJESITVE', 'Teljesítve / Beérkezett'), ('LEMONDVA', 'Lemondva')], default='TERVEZET', max_length=20, verbose_name='Státusz'),
        ),
        migrations.CreateModel(
            name='ProjectInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Anyag neve')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Készlet')),
                ('unit', models.CharField(max_length=20, verbose_name='Egység')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='projects.project')),
            ],
            options={
                'verbose_name': 'Raktárkészlet',
                'verbose_name_plural': 'Raktárkészletek',
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DailyMaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Felhasznált mennyiség')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_usages', to='projects.dailylog')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectinventory', verbose_name='Anyag a raktárból')),
            ],
        ),
    ]
