# Generated by Django 5.2.8 on 2025-11-26 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_materialorder_status_projectinventory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysettings',
            options={'verbose_name': 'Cégbeállítások', 'verbose_name_plural': 'Cégbeállítások'},
        ),
        migrations.AlterModelOptions(
            name='signatory',
            options={'verbose_name': 'Aláíró', 'verbose_name_plural': 'Aláírók'},
        ),
        migrations.RemoveField(
            model_name='companysite',
            name='site_country_code',
        ),
        migrations.RemoveField(
            model_name='companysite',
            name='site_door',
        ),
        migrations.RemoveField(
            model_name='companysite',
            name='site_floor',
        ),
        migrations.RemoveField(
            model_name='companysite',
            name='site_house_number',
        ),
        migrations.RemoveField(
            model_name='companysite',
            name='site_zip_code',
        ),
    ]
