# Generated by Django 5.2.8 on 2025-11-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_companysettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysite',
            name='site_country_code',
            field=models.CharField(default='H', max_length=5, verbose_name='Országkód'),
        ),
        migrations.AddField(
            model_name='companysite',
            name='site_door',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ajtó'),
        ),
        migrations.AddField(
            model_name='companysite',
            name='site_floor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Emelet'),
        ),
        migrations.AddField(
            model_name='companysite',
            name='site_house_number',
            field=models.CharField(default='', max_length=20, verbose_name='Házszám / HRSZ'),
        ),
        migrations.AddField(
            model_name='companysite',
            name='site_zip_code',
            field=models.CharField(default='', max_length=10, verbose_name='Irányítószám'),
        ),
        migrations.AlterField(
            model_name='companysite',
            name='site_city',
            field=models.CharField(default='', max_length=100, verbose_name='Helység név'),
        ),
        migrations.AlterField(
            model_name='companysite',
            name='site_street',
            field=models.CharField(default='', max_length=100, verbose_name='Utca név'),
        ),
    ]
