# Generated by Django 5.2.8 on 2025-11-26 17:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_alvallalkozo_options_alter_companysite_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alvallalkozo',
            options={'verbose_name': 'Alvállalkozó', 'verbose_name_plural': 'Alvállalkozók'},
        ),
        migrations.AlterModelOptions(
            name='companysite',
            options={'verbose_name': 'Telephely', 'verbose_name_plural': 'Telephelyek'},
        ),
        migrations.AlterModelOptions(
            name='masteritem',
            options={'verbose_name': 'Törzs Tétel', 'verbose_name_plural': 'Törzs Tételek'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Anyag', 'verbose_name_plural': 'Anyagok'},
        ),
        migrations.AlterModelOptions(
            name='materialorder',
            options={'ordering': ['-date'], 'verbose_name': 'Anyagrendelés', 'verbose_name_plural': 'Anyagrendelések'},
        ),
        migrations.AlterModelOptions(
            name='munkanem',
            options={'verbose_name': 'Munkanem', 'verbose_name_plural': 'Munkanemek'},
        ),
        migrations.AlterModelOptions(
            name='projectdocument',
            options={'verbose_name': 'Dokumentum', 'verbose_name_plural': 'Dokumentumok'},
        ),
        migrations.AlterModelOptions(
            name='projectinventory',
            options={'verbose_name': 'Raktárkészlet', 'verbose_name_plural': 'Raktárkészletek'},
        ),
        migrations.AlterModelOptions(
            name='signatory',
            options={'verbose_name': 'Aláíró', 'verbose_name_plural': 'Aláírók'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Beszállító', 'verbose_name_plural': 'Beszállítók'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Feladat', 'verbose_name_plural': 'Feladatok'},
        ),
        migrations.AlterModelOptions(
            name='tetelsor',
            options={'verbose_name': 'Projekt Tétel', 'verbose_name_plural': 'Projekt Tételek'},
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kapcsolattartó'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='tetelsor',
            name='gantt_duration',
            field=models.IntegerField(default=1, verbose_name='Időtartam (nap)'),
        ),
        migrations.AddField(
            model_name='tetelsor',
            name='gantt_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tervezett Kezdés'),
        ),
        migrations.AddField(
            model_name='tetelsor',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='projects.tetelsor', verbose_name='Szülő feladat'),
        ),
        migrations.AddField(
            model_name='tetelsor',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email cím'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='head_city',
            field=models.CharField(default='', max_length=100, verbose_name='Helység név'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='head_country_code',
            field=models.CharField(default='H', max_length=5, verbose_name='Országkód'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='head_door',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ajtó'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='head_floor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Emelet'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='head_house_number',
            field=models.CharField(default='', max_length=20, verbose_name='Házszám / HRSZ'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='head_street',
            field=models.CharField(default='', max_length=100, verbose_name='Utca név'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='head_zip_code',
            field=models.CharField(default='', max_length=10, verbose_name='Irányítószám'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo/', verbose_name='Céges Logó'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='name',
            field=models.CharField(default='Saját Építőipari Kft.', max_length=200, verbose_name='Cégnév'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefonszám'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Adószám'),
        ),
        migrations.AlterField(
            model_name='companysite',
            name='site_city',
            field=models.CharField(max_length=100, verbose_name='Helység név'),
        ),
        migrations.AlterField(
            model_name='companysite',
            name='site_country_code',
            field=models.CharField(default='H', max_length=5, verbose_name='Országkód'),
        ),
        migrations.AlterField(
            model_name='companysite',
            name='site_door',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ajtó'),
        ),
        migrations.AlterField(
            model_name='companysite',
            name='site_floor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Emelet'),
        ),
        migrations.AlterField(
            model_name='companysite',
            name='site_house_number',
            field=models.CharField(max_length=20, verbose_name='Házszám / HRSZ'),
        ),
        migrations.AlterField(
            model_name='companysite',
            name='site_street',
            field=models.CharField(max_length=100, verbose_name='Utca név'),
        ),
        migrations.AlterField(
            model_name='companysite',
            name='site_zip_code',
            field=models.CharField(max_length=10, verbose_name='Irányítószám'),
        ),
        migrations.AlterField(
            model_name='dailymaterialusage',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectinventory', verbose_name='Anyag a raktárból'),
        ),
        migrations.AlterField(
            model_name='dailymaterialusage',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Felhasznált mennyiség'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ANYAG', 'Anyagköltség'), ('MUNKADIJ', 'Munkadíj'), ('EGYEB', 'Egyéb')], default='ANYAG', max_length=20),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Rendelés dátuma'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Megjegyzés'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='status',
            field=models.CharField(choices=[('TERVEZET', 'Tervezet'), ('ELKULDVE', 'Elküldve'), ('VISSZAIGAZOLVA', 'Visszaigazolva'), ('TELJESITVE', 'Teljesítve / Beérkezett'), ('LEMONDVA', 'Lemondva')], default='TERVEZET', max_length=20, verbose_name='Státusz'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.supplier', verbose_name='Beszállító'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Anyag neve'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Becsült Egységár'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mennyiség'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='Egység'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Keret'),
        ),
        migrations.AlterField(
            model_name='project',
            name='callback_date',
            field=models.DateField(blank=True, null=True, verbose_name='Visszahívás'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ügyfél (Régi)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cégnév (Ha céges)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Számlázási Cím'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email cím'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefonszám'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Szerződés'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Befejezés'),
        ),
        migrations.AlterField(
            model_name='project',
            name='handover_date',
            field=models.DateField(blank=True, null=True, verbose_name='Átadás'),
        ),
        migrations.AlterField(
            model_name='project',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10, verbose_name='Rezsíóabér'),
        ),
        migrations.AlterField(
            model_name='project',
            name='hours_per_day',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=4, verbose_name='Napi óra'),
        ),
        migrations.AlterField(
            model_name='project',
            name='inquiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Beérkezés'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_company',
            field=models.BooleanField(default=False, verbose_name='Céges megrendelő?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='quote_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ajánlattétel'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Kezdés'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('UJ_KERES', '1. Új Megkeresés (Lead)'), ('FELMERES', '2. Felmérés alatt'), ('AJANLAT', '3. Ajánlattétel'), ('ELOKESZITES', '4. Projekt Előkészítés'), ('KIVITELEZES', '5. Kivitelezés (Lebonyolítás)'), ('ATADAS', '6. Műszaki Átadás-Átvétel'), ('LEZART', '7. Lezárt (Sikeres)'), ('ELUTASITVA', '8. Elutasítva / Meghiúsult'), ('TORLES_KERELEM', '9. Törlési kérelem alatt')], default='UJ_KERES', max_length=20, verbose_name='Státusz'),
        ),
        migrations.AlterField(
            model_name='project',
            name='survey_date',
            field=models.DateField(blank=True, null=True, verbose_name='Felmérés'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Adószám'),
        ),
        migrations.AlterField(
            model_name='project',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=27.0, max_digits=5, verbose_name='ÁFA %'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='category',
            field=models.CharField(choices=[('TERV', 'Tervrajz'), ('SZERZODES', 'Szerződés'), ('ENGEDELY', 'Hatósági Engedély'), ('FOTO', 'Helyszíni Fotó'), ('FELMERES', 'Felmérési Napló'), ('TELJESITES', 'Teljesítésigazolás'), ('EGYEB', 'Egyéb')], default='EGYEB', max_length=20, verbose_name='Kategória'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Leírás / Megnevezés'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='file',
            field=models.FileField(upload_to='project_docs/%Y/%m/', verbose_name='Fájl'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Feltöltve'),
        ),
        migrations.AlterField(
            model_name='projectinventory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Anyag neve'),
        ),
        migrations.AlterField(
            model_name='projectinventory',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Készlet'),
        ),
        migrations.AlterField(
            model_name='projectinventory',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='Egység'),
        ),
        migrations.AlterField(
            model_name='signatory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Név'),
        ),
        migrations.AlterField(
            model_name='signatory',
            name='position',
            field=models.CharField(default='Ügyvezető', max_length=100, verbose_name='Beosztás'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Beszállító Neve'),
        ),
        migrations.AlterField(
            model_name='tetelsor',
            name='egyseg',
            field=models.CharField(default='', max_length=20, verbose_name='Egység'),
        ),
        migrations.AlterField(
            model_name='tetelsor',
            name='leiras',
            field=models.TextField(default='', verbose_name='Leírás'),
        ),
        migrations.AlterField(
            model_name='tetelsor',
            name='master_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.masteritem', verbose_name='Törzs Tétel'),
        ),
        migrations.CreateModel(
            name='GanttLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='0', max_length=2)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='projects.tetelsor')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_links', to='projects.tetelsor')),
            ],
        ),
    ]
