# Generated by Django 5.2.8 on 2025-11-27 09:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_alvallalkozo_options_alter_companysite_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alvallalkozo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='companysettings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='companysite',
            options={},
        ),
        migrations.AlterModelOptions(
            name='masteritem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={},
        ),
        migrations.AlterModelOptions(
            name='materialorder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='munkanem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectdocument',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectinventory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='signatory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date']},
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='tetelsor',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='tetelsor',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='tetelsor',
            name='felelos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Felelős'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='head_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='head_country_code',
            field=models.CharField(default='H', max_length=5),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='head_door',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='head_floor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='head_house_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='head_street',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='head_zip_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo/'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='name',
            field=models.CharField(default='Saját Kft.', max_length=200),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='companysite',
            name='site_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companysite',
            name='site_country_code',
            field=models.CharField(default='H', max_length=5),
        ),
        migrations.AlterField(
            model_name='companysite',
            name='site_door',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companysite',
            name='site_floor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companysite',
            name='site_house_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='companysite',
            name='site_street',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companysite',
            name='site_zip_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='dailymaterialusage',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectinventory'),
        ),
        migrations.AlterField(
            model_name='dailymaterialusage',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ANYAG', 'Anyag'), ('MUNKADIJ', 'Munkadíj'), ('EGYEB', 'Egyéb')], default='ANYAG', max_length=20),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='status',
            field=models.CharField(choices=[('TERVEZET', 'Tervezet'), ('ELKULDVE', 'Elküldve'), ('VISSZAIGAZOLVA', 'Visszaigazolva'), ('TELJESITVE', 'Teljesítve'), ('LEMONDVA', 'Lemondva')], default='TERVEZET', max_length=20),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.supplier'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='callback_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='project',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='handover_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='hours_per_day',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='inquiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='quote_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('UJ_KERES', '1. Új Megkeresés (Lead)'), ('FELMERES', '2. Felmérés alatt'), ('AJANLAT', '3. Ajánlattétel'), ('ELOKESZITES', '4. Projekt Előkészítés'), ('KIVITELEZES', '5. Kivitelezés'), ('ATADAS', '6. Átadás'), ('LEZART', '7. Lezárt'), ('ELUTASITVA', '8. Elutasítva'), ('TORLES_KERELEM', '9. Törlésre vár')], default='UJ_KERES', max_length=20, verbose_name='Státusz'),
        ),
        migrations.AlterField(
            model_name='project',
            name='survey_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=27.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='category',
            field=models.CharField(choices=[('TERV', 'Tervrajz'), ('SZERZODES', 'Szerződés'), ('ENGEDELY', 'Hatósági'), ('FOTO', 'Fotó'), ('FELMERES', 'Felmérés'), ('TELJESITES', 'Teljesítés'), ('EGYEB', 'Egyéb')], default='EGYEB', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='file',
            field=models.FileField(upload_to='project_docs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projectinventory',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projectinventory',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='projectinventory',
            name='unit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='signatory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='signatory',
            name='position',
            field=models.CharField(default='Ügyvezető', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('FUGGO', 'Függőben'), ('KESZ', 'Kész')], default='FUGGO', max_length=20),
        ),
        migrations.AlterField(
            model_name='tetelsor',
            name='egyseg',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='tetelsor',
            name='leiras',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tetelsor',
            name='master_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.masteritem'),
        ),
    ]
