# Generated by Django 5.2.8 on 2025-11-27 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_alvallalkozo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tetelsor',
            options={},
        ),
    ]
