# Generated by Django 5.2.8 on 2025-11-27 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_tetelsor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysettings',
            options={'verbose_name': 'Cégbeállítások', 'verbose_name_plural': 'Cégbeállítások'},
        ),
        migrations.AlterModelOptions(
            name='masteritem',
            options={'verbose_name': 'Törzs Tétel', 'verbose_name_plural': 'Törzs Tételek'},
        ),
        migrations.AlterField(
            model_name='companysite',
            name='site_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companysite',
            name='site_street',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='UniclassNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Uniclass Kód')),
                ('title_en', models.CharField(max_length=255, verbose_name='Megnevezés (EN)')),
                ('title_hu', models.CharField(blank=True, max_length=255, verbose_name='Megnevezés (HU)')),
                ('table', models.CharField(max_length=10, verbose_name='Tábla kód')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.uniclassnode', verbose_name='Szülő kategória')),
            ],
            options={
                'verbose_name': 'Uniclass Kategória',
                'verbose_name_plural': 'Uniclass Kategóriák',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='masteritem',
            name='uniclass_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.uniclassnode', verbose_name='Uniclass Besorolás'),
        ),
    ]
