# Generated by Django 5.2.8 on 2025-11-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_companysettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysettings',
            options={},
        ),
        migrations.AlterField(
            model_name='companysite',
            name='site_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companysite',
            name='site_street',
            field=models.CharField(max_length=100),
        ),
    ]
