# Generated by Django 5.2.8 on 2025-11-27 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_companysettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Gép neve (pl. Kotró)')),
                ('unit', models.CharField(default='óra', max_length=20, verbose_name='Egység (pl. óra/nap)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Bérleti díj / Költség')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Művelet neve (pl. Kőműves)')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rezsióradíj (Ft/óra)')),
            ],
        ),
        migrations.AlterModelOptions(
            name='masteritem',
            options={},
        ),
        migrations.RemoveField(
            model_name='masteritem',
            name='cpr_kod',
        ),
        migrations.RemoveField(
            model_name='masteritem',
            name='engy_kod',
        ),
        migrations.RemoveField(
            model_name='masteritem',
            name='k_jelzo',
        ),
        migrations.RemoveField(
            model_name='masteritem',
            name='normaido',
        ),
        migrations.RemoveField(
            model_name='material',
            name='supplier',
        ),
        migrations.AddField(
            model_name='masteritem',
            name='fix_gep_ar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gép Össz.'),
        ),
        migrations.AddField(
            model_name='masteritem',
            name='fix_munkadij',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Díj Össz.'),
        ),
        migrations.AlterField(
            model_name='itemcomponent',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mennyiség'),
        ),
        migrations.AlterField(
            model_name='itemcomponent',
            name='master_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_components', to='projects.masteritem'),
        ),
        migrations.AlterField(
            model_name='itemcomponent',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.material', verbose_name='Anyag'),
        ),
        migrations.AlterField(
            model_name='masteritem',
            name='fix_anyag_ar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Anyag Össz.'),
        ),
        migrations.AlterField(
            model_name='masteritem',
            name='uniclass_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.uniclassnode'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Anyag neve'),
        ),
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Egységár'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='Egység'),
        ),
        migrations.CreateModel(
            name='MachineComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Használat (óra)')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.machine', verbose_name='Gép')),
                ('master_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_components', to='projects.masteritem')),
            ],
        ),
        migrations.CreateModel(
            name='LaborComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_required', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Normaidő (óra)')),
                ('master_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_components', to='projects.masteritem')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.operation', verbose_name='Művelet')),
            ],
        ),
    ]
