# Generated by Django 5.2.8 on 2025-11-27 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_machine_operation_alter_masteritem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masteritem',
            options={'verbose_name': 'Törzs Tétel', 'verbose_name_plural': 'Törzs Tételek'},
        ),
        migrations.AddField(
            model_name='masteritem',
            name='cpr_kod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='masteritem',
            name='engy_kod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='masteritem',
            name='k_jelzo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='masteritem',
            name='normaido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.supplier'),
        ),
        migrations.AlterField(
            model_name='itemcomponent',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemcomponent',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.material'),
        ),
        migrations.AlterField(
            model_name='laborcomponent',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.operation'),
        ),
        migrations.AlterField(
            model_name='laborcomponent',
            name='time_required',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Gép neve'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Költség'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='unit',
            field=models.CharField(default='óra', max_length=20, verbose_name='Egység'),
        ),
        migrations.AlterField(
            model_name='machinecomponent',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='machinecomponent',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.machine'),
        ),
        migrations.AlterField(
            model_name='masteritem',
            name='uniclass_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.uniclassnode', verbose_name='Uniclass'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='operation',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rezsióradíj'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Művelet neve'),
        ),
        migrations.AlterField(
            model_name='uniclassnode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.uniclassnode', verbose_name='Szülő'),
        ),
    ]
