# Generated by Django 5.2.8 on 2025-11-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_masteritem_options_masteritem_cpr_kod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniclassnode',
            name='date',
            field=models.CharField(blank=True, max_length=20, verbose_name='Dátum'),
        ),
        migrations.AddField(
            model_name='uniclassnode',
            name='description',
            field=models.TextField(blank=True, verbose_name='Leírás'),
        ),
        migrations.AddField(
            model_name='uniclassnode',
            name='extra_data',
            field=models.TextField(blank=True, verbose_name='Egyéb adatok'),
        ),
        migrations.AddField(
            model_name='uniclassnode',
            name='version',
            field=models.CharField(blank=True, max_length=20, verbose_name='Verzió'),
        ),
    ]
