# Generated by Django 5.2.8 on 2025-11-28 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_uniclassnode_date_uniclassnode_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='uniclass_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.uniclassnode', verbose_name='Uniclass (Te)'),
        ),
        migrations.AddField(
            model_name='material',
            name='uniclass_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.uniclassnode', verbose_name='Uniclass (Pr)'),
        ),
        migrations.AddField(
            model_name='operation',
            name='uniclass_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.uniclassnode', verbose_name='Uniclass (Ac)'),
        ),
        migrations.AlterField(
            model_name='masteritem',
            name='normaido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Norma (óra)'),
        ),
        migrations.AlterField(
            model_name='masteritem',
            name='uniclass_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.uniclassnode', verbose_name='Uniclass Besorolás'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Anyag neve'),
        ),
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Egységár'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='Egység'),
        ),
    ]
