# Generated by Django 5.2.8 on 2025-12-01 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_dailylogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteritem',
            name='fix_anyag_ar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='masteritem',
            name='fix_gep_ar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='masteritem',
            name='fix_munkadij',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='masteritem',
            name='normaido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='masteritem',
            name='uniclass_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.uniclassnode'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='status',
            field=models.CharField(default='TERVEZET', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='category',
            field=models.CharField(default='EGYEB', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='FUGGO', max_length=20),
        ),
        migrations.AlterField(
            model_name='tetelsor',
            name='felelos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tetelsor',
            name='gantt_duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tetelsor',
            name='gantt_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
