# Generated by Django 5.2.8 on 2025-12-02 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_alter_masteritem_fix_anyag_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Fejezet neve')),
                ('rank', models.IntegerField(default=0, verbose_name='Sorrend')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='projects.project')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.AddField(
            model_name='tetelsor',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.projectchapter', verbose_name='Fejezet'),
        ),
    ]
