# Generated by Django 5.2.8 on 2025-12-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_projectchapter_tetelsor_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tetelsor',
            name='felelos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Felelős'),
        ),
        migrations.AlterField(
            model_name='tetelsor',
            name='gantt_duration',
            field=models.IntegerField(default=1, verbose_name='Időtartam (nap)'),
        ),
        migrations.AlterField(
            model_name='tetelsor',
            name='gantt_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tervezett Kezdés'),
        ),
    ]
